repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 732c27160340466aa1b9baa0e6eaaabfb2fb76f5 # frozen: v10.0.1
    hooks:
      - id: clang-format
        types_or: [file]
        files: \.(cpp|hpp|ipp|cu|cuh|sycl|hip)$
